### ISSUE TITLE
Where to find other zip codes?

### ISSUE THREAD

**Issue by ugurduzel** [yenchiah/geo-heatmap#1]
Where can I find the bound information in this format for other zip codes?

settings["zipcode_bound_info"] = {
  "15202": [-80.108617, 40.482170, -80.033285, 40.521929, -80.070951, 40.5020495],
  "15205": [-80.172815, 40.408126, -80.040698, 40.459977, -80.106757, 40.4340515]
};

**Comment by yenchiah** [comment]
Hi, you can find the code that generates the bound information from the geo json file in the following url: https://github.com/CMU-CREATE-Lab/ehp-channel/blob/master/py/createZipcodeBoundInfo.py
